// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "Projeleri Listele",
  description: "Kullan\u0131c\u0131n\u0131n kurulu\u015Fundaki projeleri listeler. Durum, kategori, il\xE7e veya mahalleye g\xF6re filtrelenebilir.",
  inputSchema: {
    status: z.string().optional().describe("Proje durumu (\xF6r. 'In Progress', 'Completed', 'Planned')."),
    category: z.string().optional().describe("Proje kategorisi."),
    district: z.string().optional().describe("\u0130l\xE7e ad\u0131."),
    neighborhood: z.string().optional().describe("Mahalle ad\u0131."),
    limit: z.number().int().min(1).max(200).optional().describe("Maksimum kay\u0131t say\u0131s\u0131 (varsay\u0131lan 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, category, district, neighborhood, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Kimlik do\u011Frulamas\u0131 gerekli." }], isError: true };
    }
    let q = supabaseForUser(ctx).from("projects").select("id,title,status,category,district,neighborhood,budget,progress,start_date,end_date,manager_name").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (category) q = q.eq("category", category);
    if (district) q = q.eq("district", district);
    if (neighborhood) q = q.eq("neighborhood", neighborhood);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_project_default = defineTool2({
  name: "get_project",
  title: "Proje Detay\u0131",
  description: "Bir projenin t\xFCm alanlar\u0131n\u0131, notlar\u0131n\u0131 ve galerisini d\xF6ner.",
  inputSchema: {
    project_id: z2.string().uuid().describe("Proje UUID'si.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Kimlik do\u011Frulamas\u0131 gerekli." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const [{ data: project, error: pErr }, { data: notes }, { data: gallery }] = await Promise.all([
      sb.from("projects").select("*").eq("id", project_id).maybeSingle(),
      sb.from("project_notes").select("id,author,text,created_at").eq("project_id", project_id).order("created_at", { ascending: false }),
      sb.from("project_gallery").select("id,image_url,caption,sort_order").eq("project_id", project_id).order("sort_order")
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!project) return { content: [{ type: "text", text: "Proje bulunamad\u0131." }], isError: true };
    const payload = { project, notes: notes ?? [], gallery: gallery ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/add-project-note.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_project_note_default = defineTool3({
  name: "add_project_note",
  title: "Proje Notu Ekle",
  description: "Bir projeye Ba\u015Fkan Kararlar\u0131 / direktif notu ekler.",
  inputSchema: {
    project_id: z3.string().uuid().describe("Not eklenecek projenin UUID'si."),
    text: z3.string().trim().min(1).describe("Not metni."),
    author: z3.string().trim().min(1).optional().describe("Not sahibi (varsay\u0131lan: kullan\u0131c\u0131 e-postas\u0131).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ project_id, text, author }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Kimlik do\u011Frulamas\u0131 gerekli." }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("project_notes").insert({ project_id, text, author: author ?? ctx.getUserEmail() ?? "MCP" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Not eklendi." }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fzxtrslbtgfgzyibcowi";
var mcp_default = defineMcp({
  name: "kepez-projeler-mcp",
  title: "Kepez Proje Takip MCP",
  version: "0.1.0",
  instructions: "Kepez Belediyesi proje takip platformu i\xE7in ara\xE7lar. Kullan\u0131c\u0131n\u0131n kurulu\u015Funa ait projeleri listelemek, ayr\u0131nt\u0131lar\u0131 g\xF6rmek ve proje notu eklemek i\xE7in kullan\u0131n.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, add_project_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
